title: Jago Van Dam # your name (or website title) here
logo: "/images/profile_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Neuroscientist | Data Scientist 
  Data Scientist | Neuroscientist
  <br><br>
  <a href="https://www.linkedin.com/in/jago-van-dam-938ba3114">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

<style type="text/css">
h1.title {
text-align: center;
}
</style>
